# Generated by Django 5.2.4 on 2025-07-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
